### ISSUE TITLE
Option to exclude languages

### ISSUE THREAD

**Issue by carlocardella** [jeronimoek/color-picker-universal#10]
First off, nice extension 👍

I think it would be good to have an option to disable named colors for certain file types (e.g. text or markdown), it maybe improve how names colors are recognized, taking their context into account.
For example, named colors are fine in a html or css file, but not so much in a normal sentence.

Sample text file:
![image](https://user-images.githubusercontent.com/5784415/215928489-aa083d82-6ec2-41dd-96cf-f5cf2bd26989.png)
Not exactly what I would like to see when I am writing documentation or other types of prose.

To clarify, I am aware of this option:

```json
  // Set languages to be detected by the extension
  "color-picker-universal.languages": [
    "*"
  ]
```

I think another option to _exclude_ languages would be useful: in my case I would just exclude 2 file types (text and markdown), with the current option I would need to list every language I use _except_ text and markdown. The list is much longer

**Comment by jeronimoek** [comment]
Hi! Thanks for your feedback. I just released a version adding two settings, one to specify the color formats to translate from, and the other one with the formats to translate into. (This allows disabling **named** colors)
Regarding your issue, I think that disabling color formats for specific file types might take some time to pull off. But in the meantime, I think that a setting to disable languages is the best solution. I will look into it these next few days!

With regards, Jeronimo Ekerdt
