### ISSUE TITLE
Do not strip commas from RGB 

### ISSUE THREAD

**Issue by dcog989** [jeronimoek/color-picker-universal#103]
Hi. When I edit an RGB color in an XML file, the comma separators are bing stripped - i.e. `rgb(11, 22, 33) ` becomes `rgb(11 22 33)` with this extension installed. 

Is there a switch to control this or could this be provided to retain commas?

**Comment by jeronimoek** [comment]
Just uploaded a new version including this setting in the README file https://github.com/jeronimoek/color-picker-universal/pull/105
You should change the "color-picker-universal.preferLegacy" setting to `true`

**Comment by dcog989** [comment]
Perfect! Thank you very much.
