### ISSUE TITLE
[Feature Request] Please add A98 RBG (0-1) support.

### ISSUE THREAD

**Issue by WillowLockehart** [jeronimoek/color-picker-universal#106]
I create mods for video games, nowadays, I'm specifically creating mods for Baldur's Gate 3. 

The game uses the A98 RGB Colorspace, which currently requires me to use a [color picker website](https://facelessuser.github.io/coloraide/demos/colorpicker.html?color=color(a98-rgb+0.55+0.65+0.8)) to accurately get colors for. It'd be much more convenient to be able to pick them from your little interface button.

In the code block below, you'll see how the `Value` attribute uses A98 RGB to assign colors.

```xml
<node id="Vector3Parameters">
  <attribute id="Color" type="bool" value="True" />
  <attribute id="Custom" type="bool" value="False" />
  <attribute id="Enabled" type="bool" value="True" />
  <attribute id="Parameter" type="FixedString" value="Accent_Color" />
  <attribute id="Value" type="fvec3" value="0.55279124 0.027108233 0.03140889" /> <!-- A98 RGB (0-1) Color Values -->
</node>
<node id="Vector3Parameters">
  <attribute id="Color" type="bool" value="True" />
  <attribute id="Custom" type="bool" value="False" />
  <attribute id="Enabled" type="bool" value="True" />
  <attribute id="Parameter" type="FixedString" value="Cloth_Primary" />
  <attribute id="Value" type="fvec3" value="0.05 0.05 0.05" />
</node>
<node id="Vector3Parameters">
  <attribute id="Color" type="bool" value="True" />
  <attribute id="Custom" type="bool" value="False" />
  <attribute id="Enabled" type="bool" value="True" />
  <attribute id="Parameter" type="FixedString" value="Cloth_Secondary" />
  <attribute id="Value" type="fvec3" value="0.15 0.026491746 0.026491746" />
</node>
<node id="Vector3Parameters">
  <attribute id="Color" type="bool" value="True" />
  <attribute id="Custom" type="bool" value="False" />
  <attribute id="Enabled" type="bool" value="True" />
  <attribute id="Parameter" type="FixedString" value="Cloth_Tertiary" />
  <attribute id="Value" type="fvec3" value="0.3111956 0.21929227 0.17282602" />
</node>
```

**Comment by WillowLockehart** [comment]
I've been told that the format is not called linear sRGB (even though a lot of color picker websites call it that?).

Regardless, adding support for RGB(0-1), in addition to the already existing RGB(0-255) would be very much appreciated.

**Comment by jeronimoek** [comment]
WIP. It could be ready in a few days. For this, I've added a new feature to the extension, where you can configure a specific format string regex so that any exceptional case, like this one, is doable just by editing the settings.
Later I will add a section to the Readme so that it helps configure this setting

**Comment by jeronimoek** [comment]
https://github.com/jeronimoek/color-picker-universal/pull/111 
Now you should be able to use the extension with that format. It won't work by default, as this is an exceptional use case and could conflict with other users. So there are some extra steps to enable it:

Your [settings.json](https://code.visualstudio.com/docs/getstarted/settings#_settingsjson) file should contain these settings:
```json
{
  ... ,
  "color-picker-universal.customRegexes": {
    "a98": [
      "value=\"(\\d+(?:\\.\\d+)?) (\\d+(?:\\.\\d+)?) (\\d+(?:\\.\\d+)?)\"",
    ],
  },
  "color-picker-universal.maxDigits": 8
}
```
The strange string in there is a regex that matches your given a98 presentation. In case you need help understanding it you can use this website https://regexper.com/
Here is the regex above seen on that page: https://regexper.com/#value%3D%22%28%5Cd%2B%28%3F%3A%5C.%5Cd%2B%29%3F%29%20%28%5Cd%2B%28%3F%3A%5C.%5Cd%2B%29%3F%29%20%28%5Cd%2B%28%3F%3A%5C.%5Cd%2B%29%3F%29%22
Note that double quotes (") and backslash (\\) are escaped in the settings.json with a backslash (\\)
If you also want to work with alpha values show me an example and I can improve the regex.

Let me know if you find any issues.

**Comment by WillowLockehart** [comment]
Thank you very much!

**Comment by jeronimoek** [comment]
You're welcome!
