### ISSUE TITLE
can't match the color in jsx

### ISSUE THREAD

**Issue by tjx666** [jeronimoek/color-picker-universal#107]
```tsx
export function Comp() {
  console.log('rgba(0, 0, 0, 0.3)');
  return (
    <div
      style={{
        background: 'rgba(0, 0, 0, 0.3)',
      }}
    >
      hello
    </div>
  );
}

```

<img width="597" alt="image" src="https://github.com/jeronimoek/color-picker-universal/assets/41773861/1d6989eb-b096-4fd7-8864-2d13a7ccd818">

settings:

```jsonc
"color-picker-universal.languages": [
    "javascript",
    "typescript",
    "javascriptreact",
    "typescriptreact"
]
```

version:

```
Color Picker Universal: 2.2.3
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0
```

**Comment by jeronimoek** [comment]
![image](https://github.com/jeronimoek/color-picker-universal/assets/59717490/b602ace3-b859-4ca4-8452-7b08f62c9a57)
I can't reproduce on version 1.91.0, Node 20.9.0, Windows x64. Can you update and see if it still happens?

**Comment by tjx666** [comment]
Seems fixed

**Comment by jeronimoek** [comment]
What happens sometimes is that VSCode or the extension bugs, in those cases you can try restarting VSCode, or the extensions
