### ISSUE TITLE
Variable names have color picker when `ignoreVariableName` is set

### ISSUE THREAD

**Issue by nstringham** [jeronimoek/color-picker-universal#109]
# Problem

When I use a variable name in typescript it shows a color picker even though `ignoreVariableName` is set.

![image](https://github.com/jeronimoek/color-picker-universal/assets/44071655/9b96d6ae-002a-4247-a983-ff856c309e99)

# Workaround

I am working around this issue with the following config
```json
"color-picker-universal.formatsFrom": ["*", "!named"]
```

**Comment by jeronimoek** [comment]
Hi! Just uploaded a new version with a fix to this. Please let me know of any new issues

**Comment by nstringham** [comment]
A really strange thing happens where in some cases it incorrectly puts the color picker on a variable name but only if there is a syntax error.
![image](https://github.com/user-attachments/assets/9e597f29-8570-46a8-a0fa-d2df1d368d3b)

**Comment by jeronimoek** [comment]
The green variable is not detected by vscode as defined, therefore it probably is not considered a variable. I'm currently only using the vscode API to determine the variables
