### ISSUE TITLE
Why color add?

### ISSUE THREAD

**Issue by tjx666** [jeronimoek/color-picker-universal#110]
<img width="727" alt="image" src="https://github.com/jeronimoek/color-picker-universal/assets/41773861/3372b626-d87f-405f-8ee2-461c1b55ed09">

**Comment by jeronimoek-binpar** [comment]
This doesn't seem to have anything to do with the extension, what platform is this? You might have another extension causing this

**Comment by jeronimoek** [comment]
This doesn't seem to have anything to do with the extension, what platform is this? You might have another extension causing this
I will close this in the meanwhile

**Comment by jeronimoek** [comment]
I just saw your other issue, so I guess this is indeed related to the extension, I will try to reproduce the issue. If you can please share the file extension, the color picker extension configuration, and the platform (VSCode or VSCodium)
