### ISSUE TITLE
[Feature Request] Support for 0x format

### ISSUE THREAD

**Issue by zero41120** [jeronimoek/color-picker-universal#75]
I found this extension quite simple and useful.

In our project, we are using PixiJS, where the color code we provide are in 0x format.

So, instead of "#0066cc", we save as 0x0066cc as number.

The extension currently doesn't detect this. If you can add support for it, it would be great.

**Comment by jeronimoek** [comment]
Hi! I appreciate your words!
I think this is a good addition, and I will look into it asap.
Although I might ask you to save me some research time. Do you have any documentation to see exactly what values can this format hold?
I will need to determine which of these values are valid:
0xffaabb
0xfab
0xffaabbcc
0xfabc

**Comment by jeronimoek** [comment]
After some research, I think the valid format should be "0x" followed by 1 to 8 chars (0-9a-f). 

So these values would be valid:
0x0
0xab
0xabcd
0xabcdef
0xabcdef01

These would be invalid:
0x
0xkljqm
0x0123456789

Can you think of any edge case not contained here?

**Comment by jeronimoek** [comment]
This has just been released in v1.10.0, please check it out and feel free to tell me any other issues you find!

**Comment by zero41120** [comment]
Here is the PixiJS color documentation: https://pixijs.download/release/docs/PIXI.Color.html for your reference

Since 0x format is just hex number. 
The conversional CSS way, `#abc` is `#aabbcc`, however, in hex, `0xabc` is actually `0x000abc`.

![image](https://user-images.githubusercontent.com/10471270/227669164-d2a2061b-a507-4ff3-8717-ee3c3d0189d0.png)

**Comment by zero41120** [comment]
Perhaps this section can give you exact what you need in terms of conversion:
https://github.com/pixijs/pixijs/blob/a6bbda6b6d45762c05851330628e5450efd12b64/packages/color/src/Color.ts#L417-L468

**Comment by jeronimoek** [comment]
Thanks! I developed it having those same cases in mind. What I couldn't find is how could the alpha value be taken into account in such format.
Please try out the new version and let me know if there is anything missing

**Comment by zero41120** [comment]
@jeronimoek While experimenting with the settings, I noticed that the `hex_0x` value is missing from the list of available values in the main readme. However, it is included in the example.

**Comment by jeronimoek** [comment]
Nice catch! Fix will come soon!
