### ISSUE TITLE
[Bug] Named color in variable declaration

### ISSUE THREAD

**Issue by zero41120** [jeronimoek/color-picker-universal#79]
In my project, I have been using [Color Name](https://www.color-name.com/hex/) to name the colors.

Basically, if the variable name is a named color of the extension, it shows the color preview. In case of variable declaration, it should not have the preview. Since the color from the actual data is slightly different from the name. (See dodgerblue as example from this screenshot)

![image](https://user-images.githubusercontent.com/10471270/231566331-9604c51b-c86a-46da-aed0-e011a5c054f0.png)

**Comment by jeronimoek** [comment]
My proposed solution would be to add a setting enabled by default to ignore [DocumentSymbols](https://vshaxe.github.io/vscode-extern/vscode/DocumentSymbol.html), which would not provide a color picker on any variable/function/class (etc) declaration name, does it sound good to solve your case?

**Comment by jeronimoek** [comment]
There I fixed it in #80. Now there is this new setting "ignoreVariableName" (enabled by default) which tells the extension to ignore variable names. 
Please test it and let me know of any bugs. 
Thanks!
