### ISSUE TITLE
Feature request: Option to use modern (CSS colour level 4) syntax 

### ISSUE THREAD

**Issue by unikitty37** [jeronimoek/color-picker-universal#83]
When I insert a colour as HSL, it inserts `hsl(0,84%,43%)`.

This causes stylelint to complain that I am using legacy syntax: the modern syntax is `hsl(0deg 84% 43%)`.

Would it be possible to have an option to use the modern syntax where applicable?

(It would also be good to have an option to put spaces after commas, come to that — the code's much more readable with them, and people wanting to save bytes will be minifying anyway :)

**Comment by jeronimoek** [comment]
This issue is pending the resolution of this PR https://github.com/elchininet/ColorTranslator/pull/113

**Comment by jeronimoek** [comment]
In the latest release, there is the option to opt out of legacy mode. You might need to disable this setting
![image](https://github.com/jeronimoek/color-picker-universal/assets/59717490/13c3166a-2d0a-4585-9981-6986fcb511d6)
Also, the spacing issue is now fixed

**Comment by jeronimoek** [comment]
With that, I will close the issue for now, let me know if there is any other issue
