### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by v0ya** [jeronimoek/color-picker-universal#84]
- Issue Type: `Performance`
- Extension Name: `color-picker-universal`
- Extension Version: `1.11.2`
- OS Version: `Linux x64 6.4.9-arch1-1-g14`
- VSCodium version: `1.80.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/JeronimoEkerdt.color-picker-universal-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jeronimoek** [comment]
There have been some improvements in the latest release. Please check again if there is such a high CPU load
