### ISSUE TITLE
Extension show wrong color

### ISSUE THREAD

**Issue by LatenPath** [jeronimoek/color-picker-universal#94]
![image](https://github.com/jeronimoek/color-picker-universal/assets/145383056/6791aa18-50f8-4553-9898-62d8a95b8763)

In the picture, extention show the color is red when the alpha = 0.
After disable the extention, this is the one built-in VSCode :
![image](https://github.com/jeronimoek/color-picker-universal/assets/145383056/1e5e5d23-b64c-47c8-bfd3-aa6eb6df716d)

Re-enable the extention, nothing change: 
![image](https://github.com/jeronimoek/color-picker-universal/assets/145383056/c62937dc-582b-4dda-96a4-1608778ee228)

When i raise up the value, now the icon show true color:
![image](https://github.com/jeronimoek/color-picker-universal/assets/145383056/683e4312-509c-4680-941b-d046b4fb9da0)
But when I set alpha =0, it wrong again:
![image](https://github.com/jeronimoek/color-picker-universal/assets/145383056/e38241a2-9252-49ac-891a-17ee1f4f7e01)

**Comment by jeronimoek** [comment]
Hi, please install the latest version 2.1.4, and let me know if there is any other issue
